modLoader="javafml"
loaderVersion="[28,]"
issueTrackerURL="http://github.com/coolsimulations/survivalplus/issues/"
logoFile="logo.png"

[[mods]]
    modId="survivalplus"
    version="0.1.5"
    updateJSONURL="https://coolsimulations.net/mcmods/survivalplus/versionchecker.json"
    displayURL="https://curseforge.com/minecraft/mc-mods/survivalplus"
    displayName="SurvivalPlus"
    credits="To leviofpower, Jessen_House, exostealth79, and TrackaDacks who have all played a vital part in testing this mod throughout its development"
    authors="coolsim"
    description='''
    SurvivalPlus enhances the vanilla survival experience of Minecraft whilst interacting with other mods to create seamless gameplay.
    '''
[[dependencies.survivalplus]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[9.0.0.253]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="biomesoplentyextras"
    mandatory=false
    versionRange="[1.0.0]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="recycler"
    mandatory=false
    versionRange="[1.0.0]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="projecte"
    mandatory=false
    versionRange="[1.0.0]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="lumberjack"
    mandatory=false
    versionRange="[2.0.0]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="jeresources"
    mandatory=false
    versionRange="[0.10.1]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="silents_mechanisms"
    mandatory=false
    versionRange="[0.6.13,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="gemsandcrystals"
    mandatory=false
    versionRange="[1.2.7,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="trigems"
    mandatory=false
    versionRange="[1.0.1,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="emeraldobsidian"
    mandatory=false
    versionRange="[1.14.4-1.0,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="obsidiantools"
    mandatory=false
    versionRange="[2.0.2,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="vulcanite"
    mandatory=false
    versionRange="[2.04,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.survivalplus]]
    modId="carbonado"
    mandatory=false
    versionRange="[2.0.2,]"
    ordering="BEFORE"
    side="BOTH"
    